/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MedicalHistoryIndexImport } from './routes/medical-history/index'
import { Route as HospitalsIndexImport } from './routes/hospitals/index'
import { Route as AppointmentsIndexImport } from './routes/appointments/index'
import { Route as HospitalsHospitalIdImport } from './routes/hospitals/$hospitalId'
import { Route as AppointmentsBookImport } from './routes/appointments/book'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()
const DashboardLazyImport = createFileRoute('/dashboard')()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const MedicalHistoryIndexRoute = MedicalHistoryIndexImport.update({
  id: '/medical-history/',
  path: '/medical-history/',
  getParentRoute: () => rootRoute,
} as any)

const HospitalsIndexRoute = HospitalsIndexImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentsIndexRoute = AppointmentsIndexImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRoute,
} as any)

const HospitalsHospitalIdRoute = HospitalsHospitalIdImport.update({
  id: '/hospitals/$hospitalId',
  path: '/hospitals/$hospitalId',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentsBookRoute = AppointmentsBookImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/appointments/book': {
      id: '/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AppointmentsBookImport
      parentRoute: typeof rootRoute
    }
    '/hospitals/$hospitalId': {
      id: '/hospitals/$hospitalId'
      path: '/hospitals/$hospitalId'
      fullPath: '/hospitals/$hospitalId'
      preLoaderRoute: typeof HospitalsHospitalIdImport
      parentRoute: typeof rootRoute
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/hospitals/': {
      id: '/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsIndexImport
      parentRoute: typeof rootRoute
    }
    '/medical-history/': {
      id: '/medical-history/'
      path: '/medical-history'
      fullPath: '/medical-history'
      preLoaderRoute: typeof MedicalHistoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/hospitals': typeof HospitalsIndexRoute
  '/medical-history': typeof MedicalHistoryIndexRoute
}

export interface FileRoutesByTo {
  '/dashboard': typeof DashboardLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/hospitals': typeof HospitalsIndexRoute
  '/medical-history': typeof MedicalHistoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/dashboard': typeof DashboardLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/hospitals/$hospitalId': typeof HospitalsHospitalIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/medical-history/': typeof MedicalHistoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/settings'
    | '/appointments/book'
    | '/hospitals/$hospitalId'
    | '/appointments'
    | '/hospitals'
    | '/medical-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/settings'
    | '/appointments/book'
    | '/hospitals/$hospitalId'
    | '/appointments'
    | '/hospitals'
    | '/medical-history'
  id:
    | '__root__'
    | '/dashboard'
    | '/settings'
    | '/appointments/book'
    | '/hospitals/$hospitalId'
    | '/appointments/'
    | '/hospitals/'
    | '/medical-history/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardLazyRoute: typeof DashboardLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  AppointmentsBookRoute: typeof AppointmentsBookRoute
  HospitalsHospitalIdRoute: typeof HospitalsHospitalIdRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  HospitalsIndexRoute: typeof HospitalsIndexRoute
  MedicalHistoryIndexRoute: typeof MedicalHistoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardLazyRoute: DashboardLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  AppointmentsBookRoute: AppointmentsBookRoute,
  HospitalsHospitalIdRoute: HospitalsHospitalIdRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
  MedicalHistoryIndexRoute: MedicalHistoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/settings",
        "/appointments/book",
        "/hospitals/$hospitalId",
        "/appointments/",
        "/hospitals/",
        "/medical-history/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/appointments/book": {
      "filePath": "appointments/book.tsx"
    },
    "/hospitals/$hospitalId": {
      "filePath": "hospitals/$hospitalId.tsx"
    },
    "/appointments/": {
      "filePath": "appointments/index.tsx"
    },
    "/hospitals/": {
      "filePath": "hospitals/index.tsx"
    },
    "/medical-history/": {
      "filePath": "medical-history/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
